### ISSUE TITLE
Navbar Toggle doesn't work

### ISSUE THREAD

**Issue by aspiringpro** [themeteorchef/saas-stripe#17]
When you size down the navbar, the menu won't toggle. The problem is that there was no ID defined.

/client/includes/_header.html on line 13.  

The current code reads:
div class="collapse navbar-collapse

div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"

**Comment by themeteorchef** [comment]
@aspiringpro Beat ya to it! Pushed a fix for this earlier today. 

See [here](https://github.com/themeteorchef/saas-stripe/blob/master/code/client/includes/_header.html#L13). 

Can you confirm this works for you? I tested on an iPhone really quick. This is also live on the demo if you want to test their, too: http://tmc-005-demo.meteor.com.

**Comment by themeteorchef** [comment]
@aspiringpro have you had a chance to look at this yet? If so, let me know so I can confirm and close this issue :)

**Comment by aspiringpro** [comment]
Awesome man!
