### ISSUE TITLE
sanitizedError when signing up

### ISSUE THREAD

**Issue by jonwhittlestone** [themeteorchef/saas-stripe#19]
Hi,

Thanks for your work on this, 75% of the way through part one and already I've learned so much.

I've pulled the repo down and when I sign up, I am unable to get the following:

    { [Error: Match error: Expected string, got undefined]
    I20150320-08:11:53.298(0)?   message: 'Match error: Expected string, got undefined',
    I20150320-08:11:53.298(0)?   path: '',
    I20150320-08:11:53.298(0)?   sanitizedError: 
    I20150320-08:11:53.299(0)?    { [Error: Match failed [400]]
    I20150320-08:11:53.299(0)?      error: 400,
    I20150320-08:11:53.299(0)?      reason: 'Match failed',
    I20150320-08:11:53.299(0)?      details: undefined,
    I20150320-08:11:53.299(0)?      message: 'Match failed [400]',
    I20150320-08:11:53.299(0)?      errorType: 'Meteor.Error' },
    I20150320-08:11:53.299(0)?   errorType: 'Match.Error' }

And the screen doesn't progress. Any ideas?

I've signed up to Stripe (and verified my account), inputted the plans to the dashboard. I noted the other issue about a new API version but I'm assuming that's not the issue?

Any ideas appreciated, thanks.

Jon.

**Comment by jonwhittlestone** [comment]
ps. I did replace `cards` for `sources` per Matt's suggestion since I am using the `2015-02-18` version of the stripe API it seems and still no joy

**Comment by themeteorchef** [comment]
Hmm. I know what the error means, but not sure where in the flow this would be getting caught. The error has to do with the `check` package that's used to validate input passed from the client to methods on the server. Unfortunately those errors are fairly bogus and difficult to track down.

To clarify, this happened after cloning the app, running the server, and trying to sign up? Did anything else change in between that? Let me know and I'll try to help w/ debugging :)

**Comment by jonwhittlestone** [comment]
Ahh thanks for the reply.

Following this tutorial on two different machines, it had seemed I hadn't populated my stripe keys. achh.

All is good.

**Comment by themeteorchef** [comment]
Ah gotcha! That'll do it :p

Cool if I close this issue?

**Comment by jonwhittlestone** [comment]
lovely stuff thx
