### ISSUE TITLE
Demo not working in Safari/FF

### ISSUE THREAD

**Issue by robrace** [themeteorchef/saas-stripe#22]
When putting in an email that has already signed up meteor is not throwing the error back to the client. Meaning no alert or button reset. Works fine in chrome. Duplicated behavior locally too.

**Comment by robrace** [comment]
In my app I found this to be a waitOn on a non-protected page 'signup', from the Router.configure block.

**Comment by themeteorchef** [comment]
Can you paste a code snippet or link me to a repo? That will help me to debug a little easier :)

**Comment by themeteorchef** [comment]
@robrace just made a few updates and it looks like this is fixed. Testing both localhost and the demo in latest version of Safari and Firefox and I get the expected result (an alert dialog saying "email already exists"). Going to close for now but if you're still having issues let me know/reopen :)
