### ISSUE TITLE
Quite a few errors on build

### ISSUE THREAD

**Issue by johndboston** [themeteorchef/saas-stripe#23]
Hello

I'm new to programming so, most likely, there is an easy fix to my issue. When I run the application it throws various errors. I've stepped through the code and tried to trouble shoot it. I'm not having any luck. 

Any idea why these errors being thrown ? 

=> Started proxy.                             
=> Started MongoDB.                           
W20150516-19:34:55.524(-4)? (STDERR)          
W20150516-19:34:55.527(-4)? (STDERR) /Users/a/.meteor/packages/meteor-tool/.1.1.3.e283c0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150516-19:34:55.527(-4)? (STDERR) 						throw(ex);
W20150516-19:34:55.527(-4)? (STDERR) 						      ^
W20150516-19:34:55.527(-4)? (STDERR) TypeError: Cannot read property 'stripe' of undefined
W20150516-19:34:55.528(-4)? (STDERR)     at app/server/methods/stripe.js:17:37
W20150516-19:34:55.528(-4)? (STDERR)     at app/server/methods/stripe.js:328:3
W20150516-19:34:55.528(-4)? (STDERR)     at /Users/saas-stripe-master/code/.meteor/local/build/programs/server/boot.js:222:10
W20150516-19:34:55.528(-4)? (STDERR)     at Array.forEach (native)
W20150516-19:34:55.528(-4)? (STDERR)     at Function._.each._.forEach (/Users/a/.meteor/packages/meteor-tool/.1.1.3.e283c0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150516-19:34:55.529(-4)? (STDERR)     at /Users/saas-stripe-master/code/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8

**Comment by themeteorchef** [comment]
Hmm, off hand it looks like Meteor is having trouble starting up. What type of OS are your running this on (Mac or Windows)? 

Also, have you tried stopping the server and restarting?

**Comment by johndboston** [comment]
I am running it on Mac OX 10.10. 

I have tried stopping and re-running it. I kill the entire process then start again. 
I used :  kill -9 `ps ax | grep node | grep meteor | awk '{print $1}'` 

One thing I notice the first error code says the is issue is at /Users/a/.meteor/packages/.....
That's not where I'm running the application from. I'm in : 

/Users/a/saas-stripe-master/code

There isn't a .meteor directory in /a/

**Comment by johndboston** [comment]
Max osx 10.10

I did kill the process' then restart meteor. 

I can't stress enough what  newb I am. I bet I am doing something wrong.

**Comment by themeteorchef** [comment]
Ha! Don't sweat it :) Let's see here...

1.) Can you try cloning the repo into a fresh directory and seeing if you get the same error?
2.) Can you shoot me an email at ryan.glover@themeteorchef.com if that doesn't work?

If number one doesn't work, we may need to hop on a quick pair/screen share session (purpose of the email).

**Comment by themeteorchef** [comment]
Hey John, just saw this and wanted to follow up.

I spotted this error with another user. I think it has to do with your settings.json file. In there, you'll need to set the Stripe keys to be something legitimate (i.e. signup for a Stripe account and grab the API keys they give you in the dashboard). The error, here, has to do with the app trying to connect to the Stripe API using the dummy keys (`XXXXX...`) and failing to connect.

If you're still playing with this, can you give it a try for me and see if that works?

**Comment by themeteorchef** [comment]
Hey John, going to go ahead a close this for now. If you're still getting stuck, feel free to open this back up or send me an email ryan.glover@themeteorchef.com.
