### ISSUE TITLE
Issue when adding user / subscribing

### ISSUE THREAD

**Issue by danvoinea** [themeteorchef/saas-stripe#24]
I get the following error when trying to add a user via stripe. They keys are set, the plans are created with the same ids / names.

I20150523-23:11:46.270(3)? Exception while invoking method 'checkUserQuota' TypeError: Cannot read property 'plan' of undefined
I20150523-23:11:46.270(3)?     at [object Object].Meteor.methods.checkUserQuota (app/server/methods/data/read/users.js:14:44)
I20150523-23:11:46.270(3)?     at packages/check/match.js:109:1
I20150523-23:11:46.271(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:11:46.271(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150523-23:11:46.271(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150523-23:11:46.271(3)?     at _.extend.protocol_handlers.method.exception (packages/ddp/livedata_server.js:648:1)
I20150523-23:11:46.271(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:11:46.272(3)?     at packages/ddp/livedata_server.js:647:1
I20150523-23:11:46.272(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:11:46.272(3)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150523-23:11:46.277(3)? Exception while invoking method 'checkUserQuota' TypeError: Cannot read property 'plan' of undefined
I20150523-23:11:46.277(3)?     at [object Object].Meteor.methods.checkUserQuota (app/server/methods/data/read/users.js:14:44)
I20150523-23:11:46.277(3)?     at packages/check/match.js:109:1
I20150523-23:11:46.278(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:11:46.278(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150523-23:11:46.278(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150523-23:11:46.278(3)?     at _.extend.protocol_handlers.method.exception (packages/ddp/livedata_server.js:648:1)
I20150523-23:11:46.279(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:11:46.279(3)?     at packages/ddp/livedata_server.js:647:1
I20150523-23:11:46.279(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:11:46.279(3)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150523-23:11:46.283(3)? Exception while invoking method 'checkUserPlan' TypeError: Cannot read property 'plan' of undefined
I20150523-23:11:46.283(3)?     at app/server/methods/data/read/users.js:42:97
I20150523-23:11:46.284(3)?     at _.find._.detect (packages/underscore/underscore.js:184:1)
I20150523-23:11:46.284(3)?     at Array.some (native)
I20150523-23:11:46.284(3)?     at _.some._.any (packages/underscore/underscore.js:233:1)
I20150523-23:11:46.284(3)?     at Function._.find._.detect (packages/underscore/underscore.js:183:1)
I20150523-23:11:46.284(3)?     at [object Object].Meteor.methods.checkUserPlan (app/server/methods/data/read/users.js:42:28)
I20150523-23:11:46.284(3)?     at packages/check/match.js:109:1
I20150523-23:11:46.284(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:11:46.285(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150523-23:11:46.285(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150523-23:11:46.286(3)? Exception while invoking method 'checkUserPlan' TypeError: Cannot read property 'plan' of undefined
I20150523-23:11:46.286(3)?     at app/server/methods/data/read/users.js:42:97
I20150523-23:11:46.286(3)?     at _.find._.detect (packages/underscore/underscore.js:184:1)
I20150523-23:11:46.286(3)?     at Array.some (native)
I20150523-23:11:46.286(3)?     at _.some._.any (packages/underscore/underscore.js:233:1)
I20150523-23:11:46.287(3)?     at Function._.find._.detect (packages/underscore/underscore.js:183:1)
I20150523-23:11:46.287(3)?     at [object Object].Meteor.methods.checkUserPlan (app/server/methods/data/read/users.js:42:28)
I20150523-23:11:46.287(3)?     at packages/check/match.js:109:1
I20150523-23:11:46.287(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:11:46.287(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150523-23:11:46.287(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150523-23:13:13.495(3)? Exception while invoking method 'checkUserQuota' TypeError: Cannot read property 'plan' of undefined
I20150523-23:13:13.495(3)?     at [object Object].Meteor.methods.checkUserQuota (app/server/methods/data/read/users.js:14:44)
I20150523-23:13:13.496(3)?     at packages/check/match.js:109:1
I20150523-23:13:13.496(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:13:13.496(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150523-23:13:13.496(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150523-23:13:13.496(3)?     at _.extend.protocol_handlers.method.exception (packages/ddp/livedata_server.js:648:1)
I20150523-23:13:13.496(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:13:13.496(3)?     at packages/ddp/livedata_server.js:647:1
I20150523-23:13:13.497(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:13:13.498(3)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150523-23:13:13.500(3)? Exception while invoking method 'checkUserQuota' TypeError: Cannot read property 'plan' of undefined
I20150523-23:13:13.501(3)?     at [object Object].Meteor.methods.checkUserQuota (app/server/methods/data/read/users.js:14:44)
I20150523-23:13:13.501(3)?     at packages/check/match.js:109:1
I20150523-23:13:13.501(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:13:13.501(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150523-23:13:13.501(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150523-23:13:13.502(3)?     at _.extend.protocol_handlers.method.exception (packages/ddp/livedata_server.js:648:1)
I20150523-23:13:13.502(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:13:13.502(3)?     at packages/ddp/livedata_server.js:647:1
I20150523-23:13:13.502(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:13:13.502(3)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150523-23:13:13.504(3)? Exception while invoking method 'checkUserPlan' TypeError: Cannot read property 'plan' of undefined
I20150523-23:13:13.504(3)?     at app/server/methods/data/read/users.js:42:97
I20150523-23:13:13.505(3)?     at _.find._.detect (packages/underscore/underscore.js:184:1)
I20150523-23:13:13.505(3)?     at Array.some (native)
I20150523-23:13:13.505(3)?     at _.some._.any (packages/underscore/underscore.js:233:1)
I20150523-23:13:13.505(3)?     at Function._.find._.detect (packages/underscore/underscore.js:183:1)
I20150523-23:13:13.505(3)?     at [object Object].Meteor.methods.checkUserPlan (app/server/methods/data/read/users.js:42:28)
I20150523-23:13:13.505(3)?     at packages/check/match.js:109:1
I20150523-23:13:13.505(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:13:13.505(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150523-23:13:13.505(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150523-23:13:13.506(3)? Exception while invoking method 'checkUserPlan' TypeError: Cannot read property 'plan' of undefined
I20150523-23:13:13.506(3)?     at app/server/methods/data/read/users.js:42:97
I20150523-23:13:13.506(3)?     at _.find._.detect (packages/underscore/underscore.js:184:1)
I20150523-23:13:13.507(3)?     at Array.some (native)
I20150523-23:13:13.507(3)?     at _.some._.any (packages/underscore/underscore.js:233:1)
I20150523-23:13:13.508(3)?     at Function._.find._.detect (packages/underscore/underscore.js:183:1)
I20150523-23:13:13.508(3)?     at [object Object].Meteor.methods.checkUserPlan (app/server/methods/data/read/users.js:42:28)
I20150523-23:13:13.508(3)?     at packages/check/match.js:109:1
I20150523-23:13:13.508(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150523-23:13:13.508(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150523-23:13:13.509(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)

This causes some nasty errors client side(internal server error alerts - 4 of them) and doesn't update the subscription plan.

From what I could find, there's a problem in server/methods/signup.js near line 70. I tried running a console.log after the subscription variable is defined, but it doesn't work. Also, in the database, the subscription information are not filled in.

I've put it live at http://saastest.meteor.com/ and githubbed at https://github.com/danvoinea/meteor-saas.
The only thing I added was houston:admin, but I also tried without it.

How can I debug this? Thank you!

**Comment by danvoinea** [comment]
It seems it was the same issue here: https://github.com/themeteorchef/saas-stripe/issues/18 . It was because of the stripe api change. Thank you!

**Comment by themeteorchef** [comment]
@danvoinea cool, good to hear it was an easy fix! Please submit another issue if you bump into any more problems.
