### ISSUE TITLE
Base version mismatch

### ISSUE THREAD

**Issue by aldofunes** [themeteorchef/saas-stripe#25]
I will start by saying that this is the best tutorial I've found on Stripe integration (that may actually be easy to port to other payment gateways like Braintree). It is very complete and easy to follow.

When Meteor was updated to 1.2, TMC updated Base to 3.0, which changed the structure a bit. A few examples are views and controllers to templates folder. The most important, being the use of ES2015.

This tutorial is still in 1.11 or something, so the versions of the Base repo don't match. It is still easy to follow, changing a little bit the code and location of files, however the question is ¿will you update this tutorial to support Base 3.0, and Meteor 1.2?

Best regards

**Comment by themeteorchef** [comment]
Hey @aldofunes thanks for your thoughts on the recipe! 

Re: an update, there are plans for this but will be a bit before I get to it. As you noted, the big changes are mostly around structure and routes (as well as ES2015). Aside from that, the bulk of this should work okay.

I will keep this open until I do an update and send you a heads up :)

**Comment by mtwallet** [comment]
Hi Ryan. I just like to echo the thoughts of @aldotunes. I am just starting with Meteor and have found your tutorials to be some of the best I have seen. If you could update this particular recipe to use Base 3.0 that would be amazing. All that I have learned in Meteor so far has used Iron Router so I'm keen to see how you would use Flow Router within this recipe as well as amending the structure to use the existing accounts setup in Base 3.0.

Keep up the good work, your efforts are appreciated! All the best.

**Comment by themeteorchef** [comment]
Hey @mtwallet, noted! This is on my radar :)

Thanks for your thoughts.

**Comment by plaffey** [comment]
Looking forward to the update...Thanks!

**Comment by yadavpeoplelink** [comment]
I'm getting this error on server- "TypeError: Cannot read property 'stripe' of undefined".
I defined private key also.

**Comment by themeteorchef** [comment]
@yadavpeoplelink did you load the file on Meteor startup with `meteor --settings settings.json`?

**Comment by yadavpeoplelink** [comment]
ok..its working.

Thanks...

One more issue i'm facing,
I'm not getting create charge response on client. check server-side code below-

Meteor.methods({
  'chargeCard': function(stripeToken) {
      Stripe.charges.create({
      	amount: 20100,
      	currency: 'usd',
      	source: stripeToken,
      	description: "Test description"
    	}, function(err, charge) {
          return charge;
    });
  }
});

I'm getting response as 'undefined' on client side

**Comment by sonvisal** [comment]
hello sir when I clone this project it has error Your app is crashing. Here's the latest log.


/home/sonvisal/.meteor/packages/meteor-tool/.1.1.3.s0u68h++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: Cannot read property 'stripe' of undefined
    at app/server/methods/stripe.js:17:37
    at app/server/methods/stripe.js:311:3
    at /home/sonvisal/Desktop/saas-stripe/code/.meteor/local/build/programs/server/boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (/home/sonvisal/.meteor/packages/meteor-tool/.1.1.3.s0u68h++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /home/sonvisal/Desktop/saas-stripe/code/.meteor/local/build/programs/server/boot.js:117:5
Exited with code: 8
Your application is crashing. Waiting for file change.
