### ISSUE TITLE
Polish signup flow

### ISSUE THREAD

**Issue by themeteorchef** [themeteorchef/saas-stripe#7]
There are a few details that could be better about the signup flow. Specifically, I want to handle state on the signup form while we wait for Stripe as well as improve how data is being displayed in the dashboard.

**Comment by aspiringpro** [comment]
It would be awesome to include 

meteor add forwarder:autoform-wizard

with this project!

http://autoform-wizard.meteor.com

**Comment by themeteorchef** [comment]
Interesting, not familiar with this package. 

This seems like something that would be good as a fork. If you want to put an example together, let me know and I'd be glad to link it up :)
